server:
  port: 8090
#  servlet:
#    context-path: /substation
#数据库以及druid连接池配置
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.90.135.54:3305/substation?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sug
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    stat-view-servlet: #访问监控网页的登录用户名和密码
      login-username: druid
      login-password: druid
  freemarker:
    suffix: .html
    charset: utf-8

  #   关闭模板引擎
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  #redis 设置
#  redis:
#    host: 192.168.2.191 #redis 服务器地址
#    port: 6379 #redis端口
#    jedis:
#      pool:
#        max-idle: 8  #最大空闲连接
#        min-idle: 0  #最小空闲连接
#        max-wait: -1ms #连接池最大阻塞等待时间
#        max-active: 8 #连接池最大连接数
#    timeout: 5000  #连接超时时间
#    database: 0 #redis数据库索引
#    password: #默认为空

#是否启用swagger
#swagger:
#  enable: false
#mybatis设置
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sunplus.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #debug打印sql
#  日志配置
logging:
  #  path: "./log/"
  #  file: "./log/my.log"
  #  pattern:
  #    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  #    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    root: info
    com.sunplus: debug

#自定义redis key,在其他地方需要取用
#redis:
#  key:
#    prefix:
#      authCode: "portal:authCode:"
#    expire:
#      authCode: 120 #验证码超时时间